# TITLE:  Auto-Elytra
# VER.  1.1
# Author: CyberGoose
# IF BUGS FOUND:  Please contact me at https://www.spigotmc.org/members/cybergoose.854913/;
#                 I will try to resolve any bugs brought to my attention
#                 as soon as possible.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ============================================================
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Planned updates:
#   Craft-able Elytra
# ConsoleOut - relays what is enabled or not in the server terminal. (used for debugging)
# AutoGlide - the moment your elytra is equipped and you begin to fall. You automattically begin to fly.
# UseMainHand - if true hold either armor or elytra in main hand to have it autoswitch, else armor or elytra must be in
#               your offhand for it to auto switch.
# Unbreakable - sets your Elytra to unbreakable if true.
# ChestPlates - any types of armor set to false will be ignored for auto switching.
# Craftable - if set to false and you have plugins that allow you to craft an elytra, this will block that item from
#             being crafted.

 Options:
   ConsoleOut: false
   AutoGlide:  true
   UseMainHand:  false
   Unbreakable:  false
   Craftable: true
   ChestPlates:
     CHAINMAIL: true
     LEATHER: true
     GOLDEN: true
     IRON: true
     DIAMOND: true
     NETHER: true