name: AutoElytra
version: 1.1
main: me.cybergoose.autoelytra.Autoelytra
api-version: 1.15
author: Cybergoose
description: AutoElytra equips your armor or your elytra if either is held in your off hand.
